pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
        PYTHON = '/usr/bin/python3'
    }

    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/clementdevv/alx-backend-python.git',
                    branch: 'main',
                    credentialsId: 'github-creds'
                )
            }
        }

        stage('Setup Python Env') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest messaging_app/tests/ --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

    triggers {
        // Manual trigger only for now. git branch. pip3 install
    }
}
