name: CI - Django Messaging App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_pass
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r messaging_app/requirements.txt

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"$DB_HOST" -P"$DB_PORT" --silent; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Run migrations
        run: |
          source venv/bin/activate
          python messaging_app/manage.py migrate --settings=messaging_app.settings

      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest messaging_app/tests/ --ds=messaging_app.settings --junitxml=pytest-report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: pytest-report.xml
